<?php 
// $Id: explorer8_modus.module, v 1.2 2009/07/20 21:26:44 quiptime $

/**
 * @file
 * 
 * With "Explorer8 mode" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.
 */

/**
 * Implementation of hook_help().
 */
function explorer8_modus_help($path, $arg) {
  switch ($path) {
    case 'admin/settings/explorer8_modus':
      return t('With "Explorer8 mode" can be defined as the Internet Explorer 8 to display Web pages that Drupalinstallation.');
  }
}

/**
 * Implementation of hook_init().
 */
function explorer8_modus_init() {
  _explorer8_modus_header();
}

/**
 * Implementation of hook_perm().
 */
function explorer8_modus_perm() {
  return array('administer explorer8 modus');
}

/**
 * Implementation of hook_menu().
 */
function explorer8_modus_menu() {
  $items = array();
  $items['admin/settings/explorer8_modus'] = array(
    'title' => 'Internet Explorer 8 mode',
    'description' => 'Setting the document compatibility mode of the Internet Explorer 8th.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('explorer8_modus_settings'),
    'access callback' => 'user_access',
    'access arguments' => array('administer explorer8 modus'),
    'file' => 'explorer8_modus.admin.inc',
  );
  return $items;
}

/**
 * Help function.
 */
function _explorer8_modus_header() {
  if (variable_get('explorer8_modus_setting', '') == 'IE=8') {
    return '';
  }
  else {
    $data = '<meta http-equiv="X-UA-Compatible" content="' . variable_get('explorer8_modus_setting', 'IE=8') . '" />';
    drupal_set_html_head($data);
  }
}
